[package]
name = "reed_solomon_bin"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
hex = "0.4.3"
anyhow = "1.0.100"
reed_solomon = { version = "0.1.0", path = "../reed_solomon" }

[dev-dependencies]
rand = "0.9.2"
